📌 Как работает?

🔹 t-SNE хорошо работает для визуализации данных в 2D или 3D.
🔹 Он сохраняет близость точек в исходном пространстве, то есть похожие объекты остаются рядом.
🔹 Работает медленнее, чем PCA, но может выявлять скрытые кластеры в данных.
✨ Пример

Допустим, у нас есть изображения рукописных цифр (0–9). PCA может не очень хорошо отделить цифры, а t-SNE покажет чёткие кластеры (все 0 рядом, все 1 рядом и т. д.).

In [1]:
from sklearn.manifold import TSNE
import numpy as np

# Пример случайных данных (100 точек, 5 измерений)
X = np.random.rand(100, 5)

# Преобразуем в 2D
tsne = TSNE(n_components=2, perplexity=30, random_state=42)
X_2d = tsne.fit_transform(X)

print(X_2d[:5])  # Выведем первые 5 точек

[[ 1.5235424   0.95675766]
 [-0.23567934  5.074193  ]
 [ 5.346982    0.2970101 ]
 [-0.20939405 -1.1649774 ]
 [-1.4041116  -4.893645  ]]


Как работает?

🔹 MDS сохраняет расстояния между точками, а не их направление.
🔹 Если у нас есть матрица расстояний между городами, MDS сможет построить карту, даже если у нас нет координат!

In [2]:
from sklearn.manifold import MDS

mds = MDS(n_components=2, random_state=42)
X_2d = mds.fit_transform(X)

print(X_2d[:5])  # Первые 5 точек

[[ 0.37784137 -0.47971658]
 [ 0.15417497  0.29404121]
 [-0.60181379  0.35042903]
 [-0.29497042 -0.53419449]
 [-0.42756277  0.38830713]]


Как работает?

🔹 Isomap строит граф ближайших соседей и уменьшает размерность, сохраняя геометрическую форму данных.
🔹 Отлично работает для изогнутых данных (например, точки на поверхности сферы).

In [3]:
from sklearn.manifold import Isomap

iso = Isomap(n_components=2, n_neighbors=5)
X_2d = iso.fit_transform(X)

print(X_2d[:5])

[[ 0.79979733 -0.86477004]
 [-0.53403301  0.17938795]
 [ 1.03672328  0.62664464]
 [-0.55087447  0.17800877]
 [ 0.351275    0.59171333]]


📌 Как работает?

🔹 Совсем новый метод, похожий на t-SNE, но намного быстрее.
🔹 Сохраняет не только локальные, но и глобальные структуры данных.
🔹 Подходит для больших наборов данных.

In [10]:
import umap.umap_ as umap

umap_model = umap.UMAP(n_components=2)
X_2d = umap_model.fit_transform(X)

print(X_2d[:5])

[[3.2484448 7.1487074]
 [6.2198296 7.8650875]
 [1.8291483 5.963987 ]
 [6.499026  6.179993 ]
 [3.4951506 4.317644 ]]


C:\Users\zhnbk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
