In [ ]:
w = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y)

print("Веса модели:", w)

In [11]:
import numpy as np

# Вектор
v = np.array([1, 2, 3])
print("Вектор v:", v)

# Матрица
A = np.array([[1, 2], 
              [3, 4]])
print("Матрица A:\n", A)

Вектор v: [1 2 3]
Матрица A:
 [[1 2]
 [3 4]]


In [12]:
B = np.array([[5, 6],
              [7, 8]])

# Сложение
C_add = A + B
print("A + B:\n", C_add)

# Вычитание
C_sub = A - B
print("A - B:\n", C_sub)

# Умножение на число
C_scalar = 2 * A
print("2 * A:\n", C_scalar)

# Матричное умножение
C_matmul = A @ B
print("A @ B:\n", C_matmul)

# Поэлементное умножение (иногда нужно)
C_elemwise = A * B
print("A * B (поэлементное):\n", C_elemwise)


A + B:
 [[ 6  8]
 [10 12]]
A - B:
 [[-4 -4]
 [-4 -4]]
2 * A:
 [[2 4]
 [6 8]]
A @ B:
 [[19 22]
 [43 50]]
A * B (поэлементное):
 [[ 5 12]
 [21 32]]


In [17]:
# Допустим, хотим решить:
#  x + 2y = 5
# 3x + 4y = 6

A = np.array([[2, -3],
              [3, 1]])
b = np.array([8, 5])

a, c = np.linalg.solve(A, b)
print("Решение системы (x, y):", a, c)

Решение системы (x, y): 2.0909090909090913 -1.272727272727273


In [14]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [-2, -4, -6]])

B = np.array([[-3, 2, 5],
              [1, -2, 4],
              [-1, 2, 5]])

det_A = np.linalg.det(A)
det_B = np.linalg.det(B)

print("Определитель A:", det_A, det_B)

rank_A = np.linalg.matrix_rank(A)
rank_B = np.linalg.matrix_rank(B)

print("Ранг A:", rank_A, rank_B)

Определитель A: 0.0 36.000000000000014
Ранг A: 2 3


In [6]:
A_inv = np.linalg.inv(B)
print("Обратная матрица A:\n", A_inv)

Обратная матрица A:
 [[-0.5        -0.          0.5       ]
 [-0.25       -0.27777778  0.47222222]
 [ 0.          0.11111111  0.11111111]]


In [7]:


# Евклидова норма (расстояние)
dist_euclid = np.linalg.norm(x - y, ord=2)
print("Евклидово расстояние:", dist_euclid)

# Манхэттенское расстояние
dist_manhattan = np.linalg.norm(x - y, ord=1)
print("Манхэттенское расстояние:", dist_manhattan)

# Максимальное расстояние
dist_max = np.linalg.norm(x - y, ord=np.inf)
print("Максимальное расстояние:", dist_max)

NameError: name 'x' is not defined

In [8]:
dot_xy = np.dot(x, y)
norm_x = np.linalg.norm(x)
norm_y = np.linalg.norm(y)
cos_sim = dot_xy / (norm_x * norm_y)
print("Косинусная схожесть:", cos_sim)

NameError: name 'x' is not defined

In [27]:
np.corrcoef(A)

array([[1., 1.],
       [1., 1.]])

In [9]:
import numpy as np

# Сгенерируем 1000 значений из нормального распределения со ср=0, сигмой=1
data = np.random.normal(loc=0, scale=1, size=1000)

# Оценим среднее и дисперсию
mean_ = np.mean(data)
var_ = np.var(data)
print("Среднее:", mean_)
print("Дисперсия:", var_)

Среднее: 0.028871636996997255
Дисперсия: 1.0061295360065794


In [12]:
A = np.array([[1, 2, 3],
              [4, 5, 6]], dtype=float)
U, S, VT = np.linalg.svd(A, full_matrices=False)

print("U:\n", U)
print("S (вектор сингулярных значений):", S)
print("V^T:\n", VT)

# Проверим восстановление
Sigma = np.diag(S)
A_reconstructed = U @ Sigma @ VT
print("Восстановленная A:\n", A_reconstructed)

U:
 [[-0.3863177  -0.92236578]
 [-0.92236578  0.3863177 ]]
S (вектор сингулярных значений): [9.508032   0.77286964]
V^T:
 [[-0.42866713 -0.56630692 -0.7039467 ]
 [ 0.80596391  0.11238241 -0.58119908]]
Восстановленная A:
 [[1. 2. 3.]
 [4. 5. 6.]]


In [18]:
import numpy as np

def pca_numpy(X, n_components):
    # Центрирование данных
    X_mean = np.mean(X, axis=0)
    X_centered = X - X_mean

    # Вычисление ковариационной матрицы
    # Используем rowvar=False, чтобы переменные были по столбцам
    cov_matrix = np.cov(X_centered, rowvar=False)
    
    # Вычисление собственных значений и собственных векторов
    eigenvalues, eigenvectors = np.linalg.eigh(cov_matrix)
    
    # Сортировка собственных значений и векторов по убыванию
    sorted_idx = np.argsort(eigenvalues)[::-1]
    eigenvalues = eigenvalues[sorted_idx]
    eigenvectors = eigenvectors[:, sorted_idx]
    
    # Выбираем нужное число компонент
    eigenvectors = eigenvectors[:, :n_components]
    
    # Проецирование данных на выбранные компоненты
    X_reduced = np.dot(X_centered, eigenvectors)
    
    return X_reduced, eigenvalues, eigenvectors

# Пример использования:
# Создадим искусственный набор данных (5 точек в 3D пространстве)
X = np.array([
    [2.5, 2.4, 1.0],
    [0.5, 0.7, 0.3],
    [2.2, 2.9, 0.9],
    [1.9, 2.2, 0.8],
    [3.1, 3.0, 1.2]
])

# Применим PCA, сохраним 2 главных компоненты
X_reduced, eigenvalues, eigenvectors = pca_numpy(X, n_components=2)

print("Спроецированные данные (2D):\n", X_reduced)
print("\nСобственные значения (дисперсии):\n", eigenvalues)
print("\nСобственные векторы (направления главных компонент):\n", eigenvectors)

Спроецированные данные (2D):
 [[-0.46961743 -0.20554085]
 [ 2.24305009 -0.05929217]
 [-0.56744218  0.3778945 ]
 [ 0.13499996  0.06726917]
 [-1.34099045 -0.18033065]]

Собственные значения (дисперсии):
 [1.84757130e+00 5.64027859e-02 2.59096771e-05]

Собственные векторы (направления главных компонент):
 [[-0.70382423 -0.63535828]
 [-0.66688908  0.74505057]
 [-0.24472519 -0.20302586]]


In [26]:
import numpy as np

# Определим матрицу A
A = np.array([[1, 2],
              [3, 4]])

# Вычисляем собственные значения и собственные векторы
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Собственные значения:", eigenvalues)
print("Собственные векторы:\n", eigenvectors)

Собственные значения: [-0.37228132  5.37228132]
Собственные векторы:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [21]:
import numpy as np
from sklearn.decomposition import PCA

# Пример данных: 3 образца с 3 признаками
X = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Создаем объект PCA для 2-х компонент
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X)

# Вывод результата
print("Результат PCA:")
print(X_pca)


Результат PCA:
[[-5.19615242e+00 -3.62353582e-16]
 [ 0.00000000e+00 -0.00000000e+00]
 [ 5.19615242e+00 -3.62353582e-16]]
